feat: add Service provider limits and account limits to settings
jambonz/jambonz-webapp pull request #112
Opened 2022-09-21 05:19 UTC by xquanluu

2022-09-21 05:23 UTC, xquanluu commented
#109 @kitajchuk  @davehorton  Please help me to review the PR for limits feature on main branch

2022-09-21 06:13 UTC, davehorton commented
I see some errors in the console, see below

account page
![image](https://user-images.githubusercontent.com/1884973/191427656-ce073192-c449-484e-864c-d1d4825706d5.png)

and settings page

![image](https://user-images.githubusercontent.com/1884973/191427706-06eca540-adf5-45b4-8a2b-20337c423515.png)

2022-09-21 06:14 UTC, davehorton reviewed
review errors on chrome console and fix

2022-09-21 06:47 UTC, xquanluu commented
@davehorton just fixed your comments.

2022-09-21 09:32 UTC, davehorton commented
still seeing this error or warning, which I think is new
![image](https://user-images.githubusercontent.com/1884973/191469667-70ae9a23-2380-41b8-abe9-cfa5abf2bfed.png)

2022-09-21 11:21 UTC, davehorton commented
also can you move this label and field down on the account page, to just above the line with "Subspace"?

and can we make the label say "Max Concurrent Calls (0=unlimited)"

2022-09-21 11:25 UTC, xquanluu commented
Thanks @davehorton for your deep check, I fixed it for that issue.

2022-09-21 12:20 UTC, kitajchuk requested changes
I think there’s some desirable changes to be made here. See comments.

2022-09-21 12:20 UTC, kitajchuk commented on src/components/forms/AccountForm.js
> +  const limitElements = [];
This is a very strange pattern for react. Rather than do this you should map over the limits directly in the JSX tree and render each limit there.

2022-09-21 12:20 UTC, kitajchuk commented on src/components/forms/AccountForm.js
> +        {props.type === 'edit' && limitElements}
See notes on mapping instead.

2022-09-21 12:20 UTC, kitajchuk commented on src/components/forms/SettingsForm.js
> +      for (const limit of localLimits) {
Again forEach is preferable here

2022-09-21 12:20 UTC, kitajchuk commented on src/components/forms/SettingsForm.js
Also again use array map rather than this pattern.

2022-09-21 12:20 UTC, kitajchuk commented on src/components/forms/SettingsForm.js
> +          let isLimitExisted = false;
I see for this PR you are kind of trying to riff from my implementation on the refresh branch. In that case this onChange logic is overdone a bit. See what I did here:

https://github.com/jambonz/jambonz-webapp/blob/3b28d539d9fedb661d962a0f7bead07c9e92de19/src/components/local-limits.tsx#L52

2022-09-21 12:20 UTC, kitajchuk commented on src/components/forms/SettingsForm.js
> +          let isLimitExisted = false;
Looks like the difference is because I set an initial default value for the state var so maybe you’re okay with what you have here. I asked @davehorton if having an initial default is okay or not so I may have to change that on the refresh branch 🤔. Seems safe enough to have defaults since 0 equals no limit but we’ll see 🤷‍♂️

2022-09-21 12:31 UTC, kitajchuk commented on src/components/forms/SettingsForm.js
> +          let isLimitExisted = false;
Looks like no to default so ignore me on this one 🙃

2022-09-21 12:50 UTC, xquanluu commented on src/components/forms/AccountForm.js
> +  const limitElements = [];
This is because the map will need to return a single <div> tag incluse 2 elements Label and Input.
This causing the layout is moved to the left as the legacy layout is designed for 1 label on the left, 1 Input on the right

may be you have some better suggestion

2022-09-21 13:01 UTC, kitajchuk commented on src/components/forms/AccountForm.js
> +  const limitElements = [];
Yes: use a fragment to wrap the two elements so you get the desired result. Either `<>...</>` or `<React.Fragment>...</React.Fragment>`.

2022-09-21 13:07 UTC, xquanluu commented on src/components/forms/SettingsForm.js
> +      for (const limit of localLimits) {
foreach is not able to call await to make sure the call API is finished, Can you give a suggestion?

2022-09-21 13:18 UTC, kitajchuk commented on src/components/forms/SettingsForm.js
> +      for (const limit of localLimits) {
I don't know that I see why you need to use await here 🤔. You're not assigning the response data from the api call so it seems unnecessary TBH. This old application is littered with a lot of gross async/await 🙃.

2022-09-21 15:19 UTC, kitajchuk commented on src/components/forms/AccountForm.js
> +        {props.type === 'edit' && LIMITS.map(({ label, category }) => {
I think we should let them add these for add and edit 👍

2022-09-21 20:12 UTC, kitajchuk commented on package-lock.json
> +        "moment": "^2.29.4",
I suppose you can leave this in here. Looks like the folks that updated moment neglected to check in the package lock file which is why you ended up with these changes. Not your fault lol 🤷

2022-09-21 20:20 UTC, kitajchuk commented on src/components/forms/AccountForm.js
> +            value={quantity ? quantity : ""}
Seems to be an inconsistency here because if quantity is 0 then this renders an empty value. However, an empty value ends up being 0 because `Number("") === 0`. So, the question is do we render the 0 or leave this blank. Either way the 0 implies no limit on the backend, however to the user it looks like no limit is set when in fact a limit of 0 is set and returned from the backend.

2022-09-21 20:35 UTC, kitajchuk commented on src/components/forms/AccountForm.js
> +            value={quantity ? quantity : ""}
Also this is weird because 0 if falsey so I cannot manually enter a 0 into the field...

2022-09-22 07:26 UTC, davehorton approved these changes

2022-09-22 07:27 UTC, davehorton commented
looks good to me in testing.  @kitajchuk are your comments above addressed?

2022-09-22 11:24 UTC, kitajchuk commented
> looks good to me in testing. @kitajchuk are your comments above addressed?

I can check in a bit. I was hoping if we’re ready to merge the refresh branch that we could work that out first and then merge this PR into the legacy branch. Saves me one last rebase with main on the refresh branch 🤔. But I’m fine with whatever we need to do.

2022-09-22 11:39 UTC, kitajchuk requested changes
So I have some things I want removed from this PR. See my comments.

2022-09-22 11:39 UTC, kitajchuk commented on .gitignore
> +.env
We intentionally don’t ignore this base .env file. This needs to be removed from this PR. I can’t stress enough how important it is to not clutter feature PRs with random changes like this—especially flat out incorrect ones. Much like the vscode configs on the refresh branch we have this file checked into git for a reason. It’s even referenced in the readme.

Everything in this PR needs to be for the feature in question, anything else doesn’t belong here.

2022-09-22 11:39 UTC, kitajchuk commented on .env
> -REACT_APP_API_BASE_URL=http://127.0.0.1:3002/v1
Take this out and see my other comment. You should not delete this file. Seriously throwing changes like this into a feature PR is poor practice. Please keep the PRs properly in scope.

2022-09-22 11:39 UTC, kitajchuk commented on src/components/forms/AccountForm.js
> +            url: `/Accounts/${[props.account_sid]}/Limits`,
You can remove the square brackets as they are completely unnecessary.

2022-09-22 15:29 UTC, kitajchuk commented
@xquanluu @davehorton I've created the legacy branch and cleaned up the stale branches. I updated this PR to point at the legacy branch so the main branch is pencils down until I merge the refresh branch.

2022-09-22 15:52 UTC, kitajchuk commented
Oh crud, @xquanluu I forgot to pull latest on this branch before I updated it with that rebase. You'll need to get your latest changes back up here. Here's how:

```
# from your #109 branch
git fetch --all
git pull origin legacy --rebase
git push origin #109 -f
```

This should do it 🤔

2022-09-25 15:25 UTC, kitajchuk requested changes
Overall looking pretty good. I just have a couple comments on things that can be changed including one note about how you're checking `quantity` to determine post or delete method.

2022-09-25 15:25 UTC, kitajchuk commented on src/components/forms/AccountForm.js
> +          const method = l.quantity ? 'post' : 'delete';
I think you should use the empty string check here otherwise if they enter a zero you will delete the limit and it will result in rendering an empty string when the data updates which would be unexpected. Entering a zero should be valid for posting, not deleting. I see in the SettingsForm you used the empty string check so you can do it like that here as well.

2022-09-25 15:25 UTC, kitajchuk commented on src/components/forms/AccountForm.js
> +          const obj = Object.assign({
There is no need to use `Object.assign` here. In fact, you could just pass the object directly into your `axios` call and return that to clean this up a bit. Like this:

```js
return axios({
  method: method,
  baseURL: APP_API_BASE_URL,
  url: limitUrl,
  headers: {
    Authorization: `Bearer ${jwt}`,
  },
  data: method === 'post' ? l : {},
});
```

2022-09-25 15:25 UTC, kitajchuk commented on src/components/forms/AccountForm.js
> +            onChange={e => {
Nice I see you took a look at how I did this in the new app with the `LocalLimits` component 👍

2022-09-25 15:25 UTC, kitajchuk commented on src/components/forms/SettingsForm.js
> +    const obj = Object.assign({
Same thing as before—you don't need `Object.assign` here since you can just create the `obj` as a direct reference.

2022-09-26 03:42 UTC, davehorton commented on src/components/forms/AccountForm.js
> +            data: method === 'post' ? l : undefined
a more concise way to optionally include a parameter using ES6 syntax that I favor is
```
...(method === 'post && {data: l})
```

2022-09-26 07:25 UTC, kitajchuk commented on src/components/forms/AccountForm.js
> +            data: method === 'post' ? l : undefined
Ha that’s a good one. Yes this code is all compiled with babel so this is just fine 🙂

2022-09-26 13:39 UTC, davehorton commented on src/components/forms/AccountForm.js
> +            data: method === 'post' ? l : undefined
@kitajchuk are all your comments resolved?  Can I merge this now?

2022-09-26 13:46 UTC, kitajchuk requested changes
Looks like one more thing to fix real quick.

2022-09-26 13:46 UTC, kitajchuk commented on src/components/forms/SettingsForm.js
> +      ...(method === 'post' && {data: data})
This is not going to send the data for “put” requests so you’ll need to update this logic.

2022-09-26 13:50 UTC, kitajchuk commented on src/components/forms/SettingsForm.js
> +      ...(method === 'post' && {data: data})
@davehorton Not quite I noticed this callApi method is designed to not send data for “put” requests now… I think this might be the last thing to fix here. I’m on my phone tho so I admit I haven’t actually run these latest changes yet 🤔

2022-09-27 01:36 UTC, kitajchuk approved these changes

2022-09-27 01:37 UTC, kitajchuk commented
@xquanluu @davehorton this seems like it probably works now but I admit I’m on my phone and can’t test the runtime right now.

2022-09-27 07:17 UTC, merged