wip: password settings
jambonz/jambonz-webapp pull request #130
Opened 2022-10-03 13:54 UTC by xquanluu

2022-10-03 15:44 UTC, kitajchuk requested changes
Generally looks good. Just a couple of things I mentioned here that could make it feel a bit better 👍

2022-10-03 15:44 UTC, kitajchuk commented on src/containers/internal/views/settings/admin-settings.tsx
> +    if (localPasswordSettings) {
If we are not going to allow submission unless at least one field is not empty then we should manage some `required` props on the fields so that the user gets indication of what they need to do. Right now when I click Save without any fields entered on this tab nothing happens so it feels maybe broken.

2022-10-03 15:44 UTC, kitajchuk commented on src/containers/internal/views/settings/admin-settings.tsx
> +              localPasswordSettings?.require_digit &&
We do have a `hasValue` util method which is maybe preferable for making these kind of `NonNullable` checks 🤔. We also have a `hasLength` util method which is sort of the same but for "lengthy" type values.

https://github.com/jambonz/jambonz-webapp/blob/882a1bcf52193ed649aabb726e0a9de683d2867f/src/utils/index.ts#L17-L28

2022-10-03 16:21 UTC, davehorton commented
Min password has a bug - it lets me specify a value of less than 8 (it should enforce between 8-20, preferably via a dropdown)

2022-10-04 02:40 UTC, kitajchuk commented
> Min password has a bug - it lets me specify a value of less than 8 (it should enforce between 8-20, preferably via a dropdown -- although, if it is much easier to use a text input and constrain the value between 8-20 inclusive, I am ok with that)

Let’s use a select menu (drop down) then since it’s a known range. This would be the better user experience 👍.

2022-10-04 05:26 UTC, xquanluu commented on src/containers/internal/views/settings/admin-settings.tsx
> +    if (localPasswordSettings) {
yes, I see, fixed it

2022-10-04 05:28 UTC, xquanluu commented on src/containers/internal/views/settings/admin-settings.tsx
> +              localPasswordSettings?.require_digit &&
Thanks for the hint, fixed to start using the util.

2022-10-04 05:29 UTC, xquanluu commented on src/containers/internal/views/settings/admin-settings.tsx
> +    useApiData<Partial<PasswordSettings>>("/PasswordSettings");
removed it

2022-10-04 14:49 UTC, kitajchuk requested changes
Just a few icing on the cake improvements we can make on this one then it's good to go 👍

2022-10-04 23:23 UTC, xquanluu commented on src/containers/internal/views/settings/admin-settings.tsx
> +import { PasswordSettings } from "src/api/types";
I see, I will follow this rule for all next PR

2022-10-04 23:24 UTC, xquanluu commented on src/containers/internal/views/settings/admin-settings.tsx
> +        toastSuccess("Password settings was successfully updated");
I see, used: Password settings successfully updated

2022-10-04 23:26 UTC, xquanluu commented on src/containers/internal/views/settings/admin-settings.tsx
> +    setRequireDigit(
nice, fixed it

2022-10-04 23:30 UTC, xquanluu commented on src/containers/internal/views/settings/admin-settings.tsx
> +          options={Array(13)
I see, defined the constant PASSWORD_LENGTHS

2022-10-04 23:31 UTC, xquanluu commented on src/containers/internal/views/settings/admin-settings.tsx
> +            onChange={(e) => {
Applied to both require_ditgit and require_special character

2022-10-05 03:08 UTC, merged