parse jwt in the signin function to obtain values
jambonz/jambonz-webapp pull request #143
Opened 2022-10-27 08:56 UTC by EgleHelms

If we return only token in the response from the api server, we need to parse the values in the signin function.

2022-10-27 11:35 UTC, davehorton submitted a review, later dismissed

2022-10-27 13:24 UTC, davehorton commented
currently, the user_sid is one of the properties encoded in the jwt.

Does that suffice?

2022-10-27 13:27 UTC, kitajchuk commented
> currently, the user_sid is one of the properties encoded in the jwt.
> 
> Does that suffice?

Hmm. I don’t know that I like this setup much. The JWT should only be for user scope, permission and sid. The notion of force_change should not be in the JWT. Personally I think the login post should return token, sid and force_change. The usage of decoding the token for the other user data is decoupled from login so it’s generally more usable.

2022-10-27 13:33 UTC, davehorton commented
ok, np, we can make that change in jambonz-api-server

2022-10-27 13:54 UTC, kitajchuk commented
> ok, np, we can make that change in jambonz-api-server

Okay cool. @EgleHelms once that’s done you can revert the change here since we don’t need to decode JWT in the login flow. But you will need to update some typings and test utils changes made in my PR yesterday since we’re tweaking the dials here. Namely UserLogin no longer needs to extend the user interface so it can just have its own 3 fields etc. You can see the changes I made yesterday here and it should be clear how to change things as needed: https://github.com/jambonz/jambonz-webapp/pull/140/files

2022-10-27 14:51 UTC, davehorton commented
ok I pushed [this commit](https://github.com/jambonz/jambonz-api-server/commit/8d303390b7c3e003ad847dd44f4467402116196c) on the main jambonz-api-server branch.

@EgleHelms now you will need to revert back to getting force_change from the json body of the /login response, as it will not be in the jwt.

2022-10-28 08:52 UTC, EgleHelms commented
@kitajchuk is this what you had in mind? I reversed the changes and changed the typings. Ran through the tests and they work fine. Tested manually also nothing seems to have any issues logging in. The "add user" block is hidden. Anything else, I should check?

2022-10-28 11:28 UTC, davehorton approved these changes

2022-10-28 13:37 UTC, kitajchuk commented
> @kitajchuk is this what you had in mind? I reversed the changes and changed the typings. Ran through the tests and they work fine. Tested manually also nothing seems to have any issues logging in. The "add user" block is hidden. Anything else, I should check?

Lemme pull it and check later this morning. I would like to give the api changes an actual runtime check as well 👍

2022-10-28 14:50 UTC, kitajchuk requested changes
Just the changes mentioned. Sorry for the back and forth here. I expected something different from the backend changes but it's also fine the way it is 🤷‍♂️

2022-10-28 14:50 UTC, kitajchuk commented on src/api/types.ts
> +export interface UserLogin {
Looks like the backend is still returning a full payload. Based on my comment I figured we'd switch the backend to only return `{ token, user_sid, force_change }` for the login post response but it's still also returning `{ scope, permissions }` as well. So I think we need to keep this as it was using the interface extension.

```ts
export interface User {
  scope: UserScopes;
  user_sid: string;
  permissions: UserPermissions[];
}

export interface UserLogin extends User {
  token: string;
  force_change: boolean;
}
```

Based on latest from api server on `main` branch:

<img width="673" alt="Screen Shot 2022-10-28 at 7 44 50 AM" src="https://user-images.githubusercontent.com/438711/198656928-4f7aa894-6a2a-4a49-9875-0595ddfceb5e.png">

2022-11-07 17:51 UTC, EgleHelms commented on src/api/types.ts
> +export interface UserLogin {
@davehorton should I adjust the backend? I saw you added the spread of the object back, instead of just the required values. Here: https://github.com/jambonz/jambonz-api-server/commit/8d303390b7c3e003ad847dd44f4467402116196c

2022-11-08 03:40 UTC, kitajchuk commented on src/api/types.ts
> +export interface UserLogin {
I think it really doesn’t matter all that much at this point. I actually think this PR could just be closed ya?

2022-11-11 15:59 UTC, closed without merging