Add nuance speech provider
jambonz/jambonz-webapp pull request #144
Opened 2022-10-28 11:29 UTC by EgleHelms

Added to:
1. Speech provider with credentials clientId and secret (the post request works)
2. Speech Synthesis Vendor with sample mapping of the voices (need your input @davehorton)
3. Speech Recognizer Vendor (I was not sure about this, please let me know)

Question for No2 above, what values do you need to be saved, @davehorton ? Currently, this is the mapping I used:
  {
    code: "en-US",
    name: "English (United States)",
    voices: [
      { value: "allison", name: "Allison (standard)", model: "standard" },
      { value: "ava-ml", name: "Ava-Ml (enhanced)", model: "enhanced" },
    ],
  },
  
or should we have voices[0].value" filled with the object like this:
{
	"language": "ar-ww",
	"name": "Laila",
	"model": "standard",
	"gender": "female"
}

Depends on what you need here.

2022-10-28 11:36 UTC, davehorton commented
The first mapping you show above looks good.  Let me pull and test this branch and will give more feedback shortly

2022-10-28 12:33 UTC, davehorton commented
The way you are showing it in the Applications dropdown looks fine, but under Speech Synthesis I only see choices for Arabic, Basque and English at the moment.  I presume that is because you are waiting for feedback before adding the rest?

However, I realize there is something special that we will need to do for Nuance when it comes to showing voices for speech synthesis and saving them to the server.

On the server, in the Applications table we store only a language and a voice (along with vendor) for the speech synthesis (tts) choice.  For instance
```
speech_synthesis_language: "ar-WW",
speech_synthesis_vendor:  "nuance"
speech_synthesis_voice: "tarik"
```

The problem is, with nuance it is possible that they can offer same {language, voice} in both "standard" and "enhanced" model.  So somehow we need to store the model in the DB along with the voice.

I would suggest that when you POST or PUT an update to /Applications you combine the selected voice & model and submit it like this in the payload

```
speech_synthesis_voice:  "miriam - standard"
```
Accordingly, when retrieving the tts voice for an application from the db you would need to parse the model from the string and set it based on that, as far as selecting the proper item in the dropdown to select.

Does that make sense?

2022-10-28 12:44 UTC, davehorton commented
Also, there is a problem with saving a speech credential.  When we save it, we also test it and currently since you dont have a valid client_id and secret this is going to fail.  Yet see below, the UI incorrectly says the credential is valid
![image](https://user-images.githubusercontent.com/1884973/198589658-6b312586-a562-4a67-a96b-280ad16c6359.png)

2022-10-28 13:06 UTC, EgleHelms commented
Understood, take a look at the things you tested above.

Is Nuance also a Speech Recognizer? Or it is only AWS, Google and MS and Nuance should not be added there?

2022-10-28 13:14 UTC, davehorton commented
Yes, Nuance is also a recognizer so it should offer both stt and tts options (as you currently show it)

2022-10-28 13:15 UTC, davehorton commented
also @EgleHelms  can you pull the latest from the feature/nuance-speech for jambonz-api-server for your local testing?  I pushed some fixes there for returning better error info when the tts test fails

2022-10-28 13:45 UTC, EgleHelms commented
so I think I could fix the status check easily, this was just a missed check.

2022-10-28 14:06 UTC, davehorton commented
ok, let me know when all of the tts languages are in, I will retest then

2022-10-28 15:17 UTC, EgleHelms commented
I added all the languages to the map, but I am not sure if I will find a way to parse the "allison - standard" voice value today.  Since I am not totally sure where we need this exactly. The parsing should probably be in the place we are sending the data about the voice selected to the vendor. Somehow it seems like something for the backend.

2022-10-28 16:18 UTC, davehorton commented
> @davehorton I added all the languages to the map, but I am not sure if I will find a way to parse the "allison - standard" voice value today. Since I am not totally sure where we need this exactly. The parsing should probably be in the place we are sending the data about the voice selected to the vendor. Somehow it seems like something for the backend.

Good point.  Let me see what I can do on the back end.

2022-11-03 12:57 UTC, davehorton commented
@kitajchuk I would like to merge this PR, could you take a quick look and give a review?

2022-11-03 12:58 UTC, davehorton submitted a review, later dismissed

2022-11-04 13:53 UTC, kitajchuk commented
> @kitajchuk I would like to merge this PR, could you take a quick look and give a review?

Yes, sorry 😅

2022-11-04 13:59 UTC, kitajchuk requested changes
Looks good! Just the one change so we don’t have buggy label focus 👍

2022-11-04 13:59 UTC, kitajchuk commented on src/containers/internal/views/speech-services/form.tsx
> +            <label htmlFor="aws_secret_key">
This `htmlFor` should be for `nuance_secret`

2022-11-06 16:01 UTC, merged