Prefill predefined carrier gateways in a form
jambonz/jambonz-webapp pull request #147
Opened 2022-11-07 14:53 UTC by EgleHelms

Added Sip Gateway call to set a state for fetched gateways

2022-11-07 16:18 UTC, EgleHelms commented
@davehorton nope, sorry it is not ready yet. I will tag you when it is.

2022-11-07 17:39 UTC, EgleHelms commented
@davehorton @kitajchuk this is ready for review. Please take a look and test. Thank you.

2022-11-07 17:48 UTC, davehorton commented
The function of selecting a predefined carrier now works.  However, I see these errors in the console when I log in.  Do you see these as well?

![image](https://user-images.githubusercontent.com/1884973/200379460-7385eb65-7c45-43ff-8cc1-320f2a628b5f.png)

2022-11-07 18:34 UTC, davehorton commented
Yes, this works in my testing.

2022-11-07 18:34 UTC, davehorton approved these changes

2022-11-07 18:51 UTC, davehorton commented
@kitajchuk can you give a review when you get a chance?

2022-11-08 03:15 UTC, kitajchuk commented on src/api/index.ts
> -
This line doesn’t need to be removed.

2022-11-08 03:23 UTC, kitajchuk commented on src/containers/internal/views/carriers/form.tsx
> +        predefinedName.length !== 0
You should just be able to check if predefinedName is truthy like before I would suspect? It’s a string so no it should be empty or some value.

2022-11-08 03:27 UTC, kitajchuk commented on src/containers/internal/views/carriers/form.tsx
> +      const currentServiceProviderSid =
This is a really unnecessary variable. Just reference this where you need it. We should avoid creating variables that are just assigned to some available reference like this.

2022-11-08 03:30 UTC, kitajchuk commented on src/containers/internal/views/carriers/form.tsx
> +          ? predefinedCarriers?.filter((a) => a.name === predefinedName)[0]
Ha should have caught this before but you should just use the find array method here. This is a strange use of filter since really you want find 🤔

2022-11-08 03:35 UTC, kitajchuk commented on src/api/index.ts
> +  payload: void
I suspect this is okay as it looks like @davehorton has tested and reviewed this already but technically you are sending a JSON stringified body of undefined to the server since postFetch doesn’t currently assume to have no payload…

2022-11-08 03:36 UTC, kitajchuk requested changes
I think there’s at least a few reasonable changes to be made here but overall looks good 👍

2022-11-08 08:17 UTC, EgleHelms commented on src/api/index.ts
> +  payload: void
@kitajchuk would you suggest just making it a simple post request to not reuse this function?

2022-11-08 08:38 UTC, EgleHelms commented on src/api/index.ts
> -
fixed.

2022-11-08 09:00 UTC, EgleHelms commented on src/api/index.ts
> +  payload: void
@kitajchuk I refactored a bit, let me know what you think.

2022-11-08 10:13 UTC, kitajchuk commented on src/api/index.ts
> +    body: payload ? JSON.stringify(payload) : null,
I think if we want to make a change to this core function like this it would be better to omit the body entirely if it is undefined as an argument here. More like `…(payload && { body: JSON.stringify(payload) })`

2022-11-08 10:53 UTC, EgleHelms commented on src/api/index.ts
> +    body: payload ? JSON.stringify(payload) : null,
Yep, that works well. Thanks.

2022-11-08 14:12 UTC, kitajchuk commented on src/containers/internal/views/carriers/form.tsx
> +      const predefinedCarrierSid = predefinedName
Since predefinedName is known to be set five the wrapping condition I don’t think you need a ternary here. Just call the find.

2022-11-08 14:40 UTC, kitajchuk commented on src/api/index.ts
> +    ...(payload && { body: JSON.stringify(payload) }),
I think we need to make the generic here something like `Payload | undefined` don’t you think 🤔? Reasoning is we’re now saying this is a valid option for this function. Also will have a note on use of void below…

2022-11-08 14:42 UTC, kitajchuk commented on src/api/index.ts
> +  payload: void
This is not a proper use case for the void type. We should accept that payload can be undefined in the postFetch method and you can omit payload here 👍

2022-11-08 14:49 UTC, EgleHelms commented on src/api/index.ts
> +    ...(payload && { body: JSON.stringify(payload) }),
I added the undefined. I am actually surprised that typescript didn't note me on this.

2022-11-08 14:55 UTC, kitajchuk commented on src/api/index.ts
> +export const postFetch = <Type, Payload>(
I believe my intention was you would make the generic here accept undefined as well and then you can omit passing it at all below.

2022-11-08 14:56 UTC, kitajchuk commented on src/api/index.ts
> +    undefined
If you modify the generic for postFetch you can omit any payload code here since undefined would be the default of not passing a type or argument 🤔

2022-11-09 18:09 UTC, EgleHelms commented on src/api/index.ts
> +export const postFetch = <Type, Payload>(
@kitajchuk can you let me know the above?

2022-11-10 03:39 UTC, kitajchuk commented on src/api/index.ts
> +export const postFetch = <Type, Payload>(
To make payload optional I think you can do `<Type, Payload = void>`

2022-11-10 18:12 UTC, davehorton commented on src/api/index.ts
> +    undefined
@EgleHelms  is this fix still outstanding?  I'd like to see this PR get merged..

2022-11-10 18:51 UTC, EgleHelms commented on src/api/index.ts
> +export const postFetch = <Type, Payload>(
@kitajchuk the postFetch still asks for two arguments when referred to in postPredefinedCarrierTemplate

2022-11-10 19:12 UTC, EgleHelms commented on src/api/index.ts
> +export const postFetch = <Type, Payload>(
I think I figured it out.

2022-11-10 19:13 UTC, EgleHelms commented on src/api/index.ts
> +    undefined
I will ask Brandon for another rereview. Struggled with types a bit.

2022-11-11 03:03 UTC, kitajchuk approved these changes

2022-11-11 08:23 UTC, EgleHelms commented
@davehorton I think this now can be merged.

2022-11-11 12:56 UTC, merged