Feature/users dashboard
jambonz/jambonz-webapp pull request #150
Opened 2022-11-11 15:43 UTC by EgleHelms

Adding User List view on the Nav
Added filtering mechanism to the List view, currently only the search filter is working.
Added user form to implement basic add/edit/delete functionality

2022-11-11 16:12 UTC, kitajchuk commented on src/containers/internal/navi/items.ts
> +    icon: Icons.Users,
If we’re going to use this icon we should find a different one for ms teams 🤔

2022-11-11 16:13 UTC, kitajchuk commented on src/containers/internal/views/users/delete.tsx
> +    <>
This fragment is not necessary

2022-11-11 16:15 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +              Deleted account <strong>{user.name}</strong>
Should be deleted user

2022-11-11 16:16 UTC, davehorton commented on src/components/service-provider-filter.tsx
> +import React, { useEffect, useState } from "react";
eventually, we would want to be able to select by
- admin level users
- service provider level users for a given service provider
- service provider level users for a given service provider and users of accounts underneath that SP
- account level users for a given account (and by implication, service provider)
- all users

I think right now since the current focus was adding support for admin-level users we have just not implemented all of this

2022-11-11 16:17 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +  const isValidPasswd = (password: string) => {
I would prefer this is moved into untils and you pass the fetched settings as a second argument

2022-11-11 16:18 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +      result =
Also you can just return here and return false at the end, no need for the variable

2022-11-11 16:19 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +    if (user && !modal) {
What context would there be a modal?

2022-11-11 16:21 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +      getScope(user);
I don’t like this idea of a “getter” that sets state. The getter should be in utils and return the value you would set in state here.

2022-11-11 16:29 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +              type="text"
This should use the email input type

2022-11-11 16:30 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +            <label htmlFor="initialPassword">
This labels for needs to match the input id

2022-11-11 16:31 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +              <ButtonGroup>
This button should be in the other button group

2022-11-11 16:32 UTC, kitajchuk commented on src/containers/internal/views/users/index.tsx
> +const scopeSelection = [
This should be in api constants

2022-11-11 16:35 UTC, kitajchuk commented on src/containers/internal/views/users/index.tsx
> +            <div>Users</div>
We will want this UI to be more like the others with icons etc. I can help work that out. @davehorton do you think users will be very large data sets like accounts etc? I am wondering if here we could use the card view? But maybe not, you’re call 👍

2022-11-11 16:38 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +    if (!user.account_sid && !user.service_provider_sid) {
I would also change the logic here. If account sid return account. Same for service provider and return admin as default if those two are not set. This way seems more clear

2022-11-11 16:39 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +import { IMessage } from "src/store/types";
You should make this import type

2022-11-11 16:40 UTC, kitajchuk commented on src/containers/internal/api-keys/styles.scss
> +  &--col4 {
Where are we using this?

2022-11-11 16:41 UTC, kitajchuk commented on src/components/service-provider-filter.tsx
> +    "account-filter": true,
This should be changed

2022-11-11 16:42 UTC, davehorton commented on src/containers/internal/views/users/index.tsx
> +            <div>Users</div>
I think it could be as large as accounts, given that on a deployment that pushes customer self-care to the account level we'll see at least one user per account.

I have to say I don't love the card view, at least on the desktop.  Maybe its just that I'm not used to seeing it in other products

2022-11-11 16:43 UTC, kitajchuk commented on src/styles/_filters.scss
> +  &--mix {
You could remove this and just pair the ender and multi classes 👍

2022-11-11 16:45 UTC, kitajchuk commented on src/styles/index.scss
> +  color: var(--jambonz);
This should not be here. Apply the color where you need it contextually. This is to remain a very generic className 👍

2022-11-11 16:46 UTC, kitajchuk commented on src/containers/internal/views/users/index.tsx
> +            <div>Users</div>
Lol fair enough. I’ll let it die 😅🙃

2022-11-11 16:52 UTC, kitajchuk commented on src/components/service-provider-filter.tsx
> +import React, { useEffect, useState } from "react";
Okay that’s helpful and also complex lol. So for now what is this service provider filter doing? Filtering only by service provider sid? Is this what we want for now?

2022-11-11 17:35 UTC, davehorton commented on src/components/service-provider-filter.tsx
> +import React, { useEffect, useState } from "react";
For now, I think the service provider filter should let you either choose "all" or a specific, single service provider.  (I think it needs to be a dropdown).  I dont think there will ever be a need to filter in a way that selects more than one service provider.

So yes I think this is what we want for now.

If you do select a service provider, then you should definitely see all the users for that service provider in the tableview.  The account dropdown should offer you some choices that _may_ add some other users into the filtered tablesview
- service provider users only (nothing added)
- specific account (showing name in dropdown) - adds in users for the selected accounts
- all accounts - adds in users from all accounts under this service provider

I

2022-11-11 17:47 UTC, kitajchuk commented on src/components/service-provider-filter.tsx
> +import React, { useEffect, useState } from "react";
Okay that seems fairly straightforward for now. @EgleHelms we have examples of combination filters (search+account) on other list views. We leverage memo for the results so it’s a combo thing. This one is different in that there are two filters being applied on top of the fuzzy search. Give it a shot and just reach out if you have questions or need help 👍

2022-11-14 10:01 UTC, EgleHelms commented on src/containers/internal/api-keys/styles.scss
> +  &--col4 {
I kind of reused the API keys table design to achieve this view for users:
![image](https://user-images.githubusercontent.com/63853378/201631651-254766a6-7946-40b9-a2b2-afcbf8e7ddd1.png)

2022-11-14 10:03 UTC, EgleHelms commented on src/containers/internal/navi/items.ts
> +    icon: Icons.Users,
when do you see this icon that refers to the ms teams? Is it ever part of the navigation?
Do you really think it will be confusing?

2022-11-14 10:41 UTC, EgleHelms commented on src/containers/internal/views/users/form.tsx
> +    if (user && !modal) {
When you would click on "Delete user" a modal would come up and for some reason would run the "handleSubmit", I am actually not sure why it is run. Since onClick only changes the modal value to true and according to that we show the modal. WHen the modal is shown the handleSubmit is automatically run, but the handleSubmit is a prop we pass to the DeleteUser component which is the handleDelete function.

2022-11-14 11:25 UTC, EgleHelms commented on src/containers/internal/views/users/form.tsx
> +              <ButtonGroup>
so with the current code it look like this:
![image](https://user-images.githubusercontent.com/63853378/201648176-5c4a6aaa-93af-4f09-875d-b9cdafdcecd1.png)

If I add it to the existing btn group it look slike this:
![image](https://user-images.githubusercontent.com/63853378/201648309-b11a7fc1-49b7-4031-8011-7440dced8569.png)

Let me know if I should leave it this way.

2022-11-14 11:32 UTC, EgleHelms commented on src/containers/internal/views/users/index.tsx
> +            <div>Users</div>
making no changes here.

2022-11-14 11:58 UTC, EgleHelms commented on src/styles/_filters.scss
> +  &--mix {
I was trying to reuse the styles already written combined, but it was adding extra space this way. Then I need to make the below code conditional somehow. Since I don't want to mess up the other filters. Seems the "Recent calls" one will be affected.

```
    > :first-child {
      margin-left: auto;
    }
```

2022-11-14 15:12 UTC, EgleHelms commented on src/components/service-provider-filter.tsx
> +import React, { useEffect, useState } from "react";
This was my take on the filtering.

2022-11-14 17:24 UTC, EgleHelms commented on src/containers/internal/views/users/index.tsx
> +  }, [
@kitajchuk this was my approach to filtering - this is still not working as I expect. Issues this filter still currently has:
- filtering works only if it is applied one after the other.
- after I select the filters, changing the value of the filter again will not filter correctly. You need to select "all" again and you can then filter again
- we should fetch accounts from the api only after receiving the serviceProviderSid, to get them only for that provider. but I am not able to get the values inside the useMemo.

2022-11-15 03:35 UTC, kitajchuk commented on src/containers/internal/navi/items.ts
> +    icon: Icons.Users,
It is part of the navigation. To see it you need to add an FQDN for the currently service provider and it’s the last item in the BYO section. Yes we should use different icons for these two navigation items. I can poke at feather icons and see what I think 🤔

2022-11-15 03:36 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +    if (user && !modal) {
This sounds odd. I’ll look again because it should not be the case that this happens like that 🤔

2022-11-15 03:38 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +              <ButtonGroup>
I think it should be in the group but the last item and aligned right. Also probably gray vs the dark. We have a delete button on the service provider settings as an example.

2022-11-15 03:41 UTC, kitajchuk commented on src/containers/internal/api-keys/styles.scss
> +  &--col4 {
Oh. Idk about this. It doesn’t feel like any of our other list views. I’d prefer to see it more like that. I’m not sure why SID is important here because it’s not elsewhere? I would drop it and make this feel like our other lists with icons 🤔. But maybe @davehorton  feels differently?

2022-11-15 03:43 UTC, kitajchuk commented on src/containers/internal/api-keys/styles.scss
> +  &--col4 {
I see that’s fair enough

2022-11-15 03:43 UTC, kitajchuk commented on src/styles/_filters.scss
> +  &--mix {
I see that’s fair enough

2022-11-15 03:47 UTC, kitajchuk commented on src/containers/internal/views/users/index.tsx
> +  }, [
There should not be a none for service provider. Most views rely on fetching data based on current service provider. In fact we found a lot of scenarios where that was not happening and fixed it during the rewrite. But not all cases. @davehorton is the source of requirements there. I can pull this branch and actually run code and test to provide better feedback on this probably tomorrow morning.

2022-11-15 03:52 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +                <ButtonGroup>
This should not be a nested button group. Just put the delete button only in the parent group.

2022-11-15 03:57 UTC, kitajchuk commented on src/containers/internal/views/users/index.tsx
> +            <Pagination
Is this actually a paginated result set? If so then this should work quite a bit differently since you are fetching the users flat with an api call. You can see how we do paginated data in recent calls and alerts but that data is paginated on the backend. If this is not actually a paginated response from the backend then a lot of code was copy pasted here that should not be here…

2022-11-15 03:58 UTC, kitajchuk commented on src/styles/_forms.scss
> +  &--filter {
What is this for?

2022-11-15 04:00 UTC, kitajchuk commented on src/utils/index.ts
> +export const getUserScope = (user: User) => {
You could specify the return type here so it’s not just inferred as a string 🤔

2022-11-15 08:41 UTC, EgleHelms commented on src/containers/internal/api-keys/styles.scss
> +  &--col4 {
Initially, I made it like the Application/Account list ones and @davehorton asked me to change it to a table-like view so I reused the API keys one. We can change that to be more like that table with a simpler "Edit" button (Similar to "Delete" in API keys) and I can omit the SID to make it more like the API key table so it is more streamlined. Let me know.

2022-11-15 08:45 UTC, EgleHelms commented on src/containers/internal/views/users/index.tsx
> +  }, [
@kitajchuk I would be super grateful. I will still tinker around with the filter today to see if I can still make the filter better on my own.
Regarding the Service Provider selection - I understood as much. 
@davehorton what role do you think the current "service provider" plays in the view of the User list?

2022-11-15 11:49 UTC, EgleHelms commented on src/containers/internal/views/users/index.tsx
> +            <Pagination
I thought I might be able to reuse it, so I copied it in for reference as something still to do. 
But yeah, this seems to only be designated for query calls. Clear, will remove it.

2022-11-15 12:17 UTC, davehorton commented on src/containers/internal/api-keys/styles.scss
> +  &--col4 {
I dont think the user sid would be required in the table/listview

2022-11-15 12:24 UTC, davehorton commented on src/containers/internal/views/users/index.tsx
> +  }, [
I dont think we can or should list "admins" as a selection in the main service provider dropdown.  So much of the entire UI depends on their being a current, single, service_provider_sid and I dont want to change that.

@EgleHelms I am fine with your idea of removing the service provider filter and filtering by the "current service provider".  In that case, for an admin user, the list view would encompass all admin users + all users of the current service provider + all users of subsidiary accounts.  I suppose then the controls needed would be
- checkbox: whether or not to show admin users
- dropdown: list of accounts, including a selection for "none" or "all".

Do you agree?

2022-11-15 13:04 UTC, EgleHelms commented on src/containers/internal/views/users/index.tsx
> +  }, [
@davehorton I agree with most of the things, but maybe it also makes sense to have the scope listed in the table + be able to select from dropdown like this:
![image](https://user-images.githubusercontent.com/63853378/201922592-09f04433-1c4b-45c3-8d30-fd71a8f84df5.png)

This way this filter will be useful in all views of all users. To know what user has what scope at any point

2022-11-15 14:21 UTC, EgleHelms commented on src/containers/internal/views/users/form.tsx
> +    if (user && !modal) {
Would be super helpful.

2022-11-15 14:34 UTC, EgleHelms commented on src/styles/index.scss
> +.btns--spaced {
I added this to space buttons like this, not sure how to do it otherwise for the ButtonGroup:
![image](https://user-images.githubusercontent.com/63853378/201945232-b2695343-e564-4ba3-9978-d241c2f32726.png)

2022-11-15 14:34 UTC, kitajchuk commented on src/containers/internal/navi/items.ts
> +    icon: Icons.Users,
Ya I think we should change the teams icon.

2022-11-15 14:37 UTC, EgleHelms commented on src/containers/internal/api-keys/styles.scss
> +  &--col4 {
@kitajchuk @davehorton but do you both agree on this view? 

![image](https://user-images.githubusercontent.com/63853378/201946182-75a83085-3958-497d-b824-d50453e4396a.png)

2022-11-15 14:49 UTC, kitajchuk commented on src/containers/internal/api-keys/styles.scss
> +  &--col4 {
You should be able to delete here like the other list views as well. I’ll smoke and poke this branch in a bit and see how this layout handles responsively

2022-11-15 15:39 UTC, EgleHelms commented on src/containers/internal/api-keys/styles.scss
> +  &--col4 {
@kitajchuk I had it like this before - for some reason icons aligned in the same way were not actually aligned, but would this be ok, see below?
![image](https://user-images.githubusercontent.com/63853378/201961367-83ecb759-b30b-42e0-a59a-6f80b0060c9b.png)

2022-11-15 16:01 UTC, EgleHelms commented on src/containers/internal/navi/items.ts
> +    icon: Icons.Users,
Maybe one of these could work for Teams Tenants?
||||
|--|--|--|
|![image](https://user-images.githubusercontent.com/63853378/201966043-4ec2c855-01bc-4c4f-a612-63daa134aca8.png) |![image](https://user-images.githubusercontent.com/63853378/201966168-fe228a5d-2b5d-4cf3-9e89-f157d5b05c33.png)| ![image](https://user-images.githubusercontent.com/63853378/201966236-6ef868c1-5123-480f-92ef-cd6afffbce0b.png)|

2022-11-16 10:15 UTC, EgleHelms commented on src/containers/internal/views/users/form.tsx
> +    if (user && !modal) {
I added this check directly to the handleSubmit to avoid this.

2022-11-16 14:05 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +    if (user && !modal) {
I think you just need to add type=button to the delete button. The default type for a button is submit so my guess is it’s trying to also submit the form. I’d you do that you can remove this check here. We need to be careful with non-submit buttons in the forms 👍

2022-11-16 14:15 UTC, kitajchuk commented
@EgleHelms been busy and unable to run this branch yet for a proper review there. Hoping to be able to do that today 🤞

2022-11-16 16:03 UTC, kitajchuk commented on src/components/index.ts
> +import { ServiceProviderFilter } from "./service-provider-filter";
If we're not using the service provider filter right now than we should trash it please.

2022-11-16 16:06 UTC, kitajchuk commented on src/containers/internal/api-keys/styles.scss
> +    .grid__row {
This whole grid scss file should now be moved to root styles and imported in the main styles index like other global things. You can remove the import in api-keys then also.

2022-11-16 16:07 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +    const decodedJwt = parseJwt(getToken());
We should not be parsing the JWT here. That is done when you log in. You should be selecting the user state from the global store.

2022-11-16 16:11 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +      localStorage.clear();
You need to be using the `signout` method from our `useAuth` context provider for this. Example is in the root internal layout but looks like this: `const { signout } = useAuth();`. Then just call `signout()` and be done.

2022-11-16 16:14 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +                <Button small subStyle="grey" onClick={() => setModal(true)}>
Ya just add `type="button"` to this and you don't need to check the modal state var in the submit handler 👍

2022-11-16 16:15 UTC, kitajchuk commented on src/containers/internal/views/users/index.tsx
> +          account.account_sid === e.account_sid;
You need to actually return the value here for `every`. This syntax is not returning your comparison operator since you're using bracket notation for the arrow function. So more like `accounts?.every((account) => account.account_sid === e.account_sid)`.

2022-11-16 16:17 UTC, kitajchuk commented on src/containers/internal/views/users/index.tsx
> +          return scopeFilter === "all" && !accountSid
This is hard to read and grock easily. I might be more of a fan of a straight forward function block with clear if syntax and multiple returns for each condition for clarity here.

2022-11-16 16:18 UTC, kitajchuk commented on src/containers/internal/views/users/index.tsx
> +      <Section {...(hasLength(filteredUsers) && { slim: true })}>
You can remove this conditional prop and just always have the `slim` prop on this view. With the tables we need it like that or you will get double padding on the empty views like this:

<img width="1169" alt="Screen Shot 2022-11-16 at 7 48 47 AM" src="https://user-images.githubusercontent.com/438711/202235182-36148c8a-ec97-471f-bc6b-c119a3bc7c75.png">

2022-11-16 16:19 UTC, kitajchuk commented on src/containers/internal/views/users/index.tsx
> +            <div>Users</div>
This should be `Name` for the column label 🤔

2022-11-16 16:26 UTC, kitajchuk commented on src/containers/login/create-password.tsx
> +    if (passwdSettings && !isValidPasswd(password, passwdSettings)) {
Not that I have a great answer for this but I'm curious what we would do here if `PasswordSettings` response failed and this was never set. Seems edge case but a thought nonetheless 🤔

2022-11-16 16:28 UTC, kitajchuk commented on src/store/actions.ts
> +  const { user_sid, permissions, scope, force_change, is_active, name, email } =
If these are all the values that are encoded in the JWT then we can just return `parseJwt(token)` and avoid the destructuring nonsense here 👍

2022-11-16 16:33 UTC, kitajchuk commented on src/containers/internal/navi/items.ts
> +    icon: Icons.Users,
I think we keep the users icon for teams and do user plus or user check for the users view.

2022-11-17 10:01 UTC, EgleHelms commented on src/containers/internal/navi/items.ts
> +    icon: Icons.Users,
changed to usersCheck icon.

2022-11-17 10:03 UTC, EgleHelms commented on src/components/index.ts
> +import { ServiceProviderFilter } from "./service-provider-filter";
trashed

2022-11-17 10:11 UTC, EgleHelms commented on src/containers/internal/api-keys/styles.scss
> +    .grid__row {
moved

2022-11-17 10:26 UTC, EgleHelms commented on src/containers/login/create-password.tsx
> +    if (passwdSettings && !isValidPasswd(password, passwdSettings)) {
added a constant to api/constants and added it as a fallback value.

2022-11-17 10:34 UTC, EgleHelms commented on src/containers/internal/views/users/index.tsx
> +            <div>Users</div>
@kitajchuk sorry, not sure what you mean here.

2022-11-17 10:36 UTC, EgleHelms commented on src/containers/internal/views/users/index.tsx
> +            <div>Users</div>
oh ok, got it... just that the label should be Name not user, since we list names under it.

2022-11-17 10:53 UTC, EgleHelms commented on src/styles/index.scss
> +  > :nth-child(3) {
This does not work in this case.
This refers to the Cancel/Save/Delete buttons in both edit and new user forms. In a new user form Delete button does not exist. Thus the last-child is Save and is spaced.

2022-11-17 10:56 UTC, EgleHelms commented
@kitajchuk I think I will branch of this branch to continue with the next part of the implementation (creating scope-specific users, hiding elements according to user scope, other small improvements of the current implementation) since this is getting really big PR and I don't think it is ready to merge, since the api-server branch is also not merged yet.

2022-11-17 12:59 UTC, kitajchuk commented on src/styles/index.scss
> +  > :nth-child(3) {
I would apply this className conditionally then and use last child

2022-11-17 14:44 UTC, EgleHelms commented on src/styles/index.scss
> +  > :nth-child(3) {
done

2022-11-21 10:35 UTC, EgleHelms commented
@kitajchuk this is now ready for your re-review.

I have added changes from the PR I have closed for now, since we agreed to finalize this:
- allow creating scoped users in the form
- improve the temporary password field
- remove delete button from the Users list as per agreement with @davehorton 

I will start improving <AccessControl> component and applying it in another branch. If you have some specifications for me, please create an Issue with a detailed description and assigned me there. This way maybe we can reach agreements on things a bit quicker.

2022-11-22 09:01 UTC, EgleHelms commented
@kitajchuk @davehorton can you please re-review this? Dave mentioned we can merge it if this is in order.

2022-11-22 15:43 UTC, kitajchuk requested changes
Okay some more changes to see here but close 👍

2022-11-22 15:43 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +      passwdCheck();
You need to return true/false in this method and use that to return here. Returning in the called method will not stop this function block from executing which I imagine we want to do if password is invalid 🤔

2022-11-22 15:43 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +      if (initialPassword) {
Same you need to actually return in this function block to stop the api call…

2022-11-22 15:43 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +                    currentUser?.scope === "service_provider"
I don’t like this because it’s unclear and if the order changes this would fail us. We do something like this in applications form with vendor options but we use array filter so the things we are excluding are explicit.

2022-11-22 15:43 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +          scope === "admin" && currentUser?.scope === "admin"
I think at this point I’d like to see these scope strings as constants similar to how we do with vendors. This would mean updating to use said constants anywhere we are referencing these string values.

2022-11-22 15:43 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +            {accounts && accounts.length && scope === "account" ? (
You can replace this first part with our hasLength(accounts) utility method.

2022-11-22 15:43 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +            <Passwd
You need to pass id=“ initial_password” to this component for the label to focus it

2022-11-22 15:43 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +              {user && (
Probably should be user && user.data && …

2022-11-22 15:43 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +            {accounts && accounts.length && scope === "account" ? (
I also don’t think the ternary is necessary since these conditions require opposite regarding scope equal or not to account. You can just make them each their own conditional render line. It’s preferential to avoid ternary in render IMO if possible 🤔

2022-11-23 13:58 UTC, EgleHelms commented
@kitajchuk thanks. I am learning so much :) This is again ready for re-review.

2022-11-23 15:39 UTC, kitajchuk commented on src/containers/internal/views/users/form.tsx
> +                    value={"No accounts."}
Heh, no need for brackets around string props

2022-11-23 15:46 UTC, kitajchuk approved these changes
I’m approving this but can you please address the couple simple comments before merging 🙏

2022-11-23 15:49 UTC, kitajchuk commented
Also @davehorton are we intending to merge this to main?

2022-11-23 15:59 UTC, davehorton commented
> Also @davehorton are we intending to merge this to main?

Yes

2022-11-23 15:59 UTC, davehorton submitted a review, later dismissed

2022-11-23 16:16 UTC, kitajchuk commented
> > Also @davehorton are we intending to merge this to main?
> 
> Yes

Sweet smash the button

2022-11-23 18:12 UTC, merged