ScopeAccess component implementation
jambonz/jambonz-webapp pull request #154
Opened 2022-11-24 15:31 UTC by EgleHelms

@kitajchuk this is my try to implement what you described in mind with a simple component, plus applied it as an example in one place which works well in the app itself. I also added a similar cypress test, but that one does not render for some reason, maybe you can spot why with your pro eyes :).

I was not exactly sure about the hook and what exactly you meant about that. 

Let me know your thoughts. And many thanks for guiding me.

2022-11-24 16:19 UTC, kitajchuk requested changes
Some changes. For the tests to work you will have to mock the user scope and login since that’s not the default. You can see the test utils here: https://github.com/jambonz/jambonz-webapp/blob/main/src/test/index.tsx. This may be a bit more challenging since we don’t currently do a login example in any of our component tests.

We don’t currently have any flows for this. To test scopes we’d need to be able to mock the store more flexibly for our tests.

You notice currently we allow passing auth context props but we use the store provider verbatim. We’d need to use the store context similar to how we do with auth in the test provider and support passing store props as well. May be more trouble than it’s worth for this PR but you could take a shot st it if you want. I would separate them out as authProps and storeProps on the test provider. If you do you may have to update other tests to pass props the new way.

2022-11-24 16:19 UTC, kitajchuk commented on src/store/types.ts
> +export enum Scope {
This should be reversed so that admin is the highest numeric value

2022-11-24 16:19 UTC, kitajchuk commented on src/store/actions.ts
> +import { Scope } from "./types";
Idk why the imports changed like this. You could have just added Scope to the type imports above and there was no need to change the other one.

2022-11-24 16:19 UTC, kitajchuk commented on src/containers/internal/navi/index.tsx
> +          </ScopedAccess>
Can you do me a favor and remove the below stuff regarding the user that is intentionally not rendered. This is old and won’t be used ever. You can also remove react-blockies from the package.json 👍

2022-11-24 16:19 UTC, kitajchuk commented on src/containers/internal/navi/index.tsx
> +                  <option>currentServiceProvider.name</option>
Why? This was intentional since the current SP is reliant on an async request. In fact, the ternary implies that it’s not set, so undefined, in this else block so this should not have been changed…

2022-11-24 16:19 UTC, kitajchuk commented on src/components/scoped-access.tsx
> +
I don’t think we need this so it can be removed. You either have access to things or you don’t and there’s no reason to show people a message about what they can’t access.

2022-11-24 16:19 UTC, kitajchuk commented on src/components/scoped-access.tsx
> +  enumScope: Scope;
Would prefer to just call this prop scope

2022-11-24 16:19 UTC, kitajchuk commented on src/components/scoped-access.cy.tsx
> +    cy.mount(<ScopedAccessTestWrapper enumScope={1} />);
Anywhere you use the scope prop you should be using the enum rather than raw numbers as a value

2022-11-24 16:19 UTC, kitajchuk commented on src/api/types.ts
> +  enumScope: Scope;
I don’t think we should put this here since this is supposed to be an interface for the api response and this enum is purely a client-side thing.

2022-11-24 16:19 UTC, kitajchuk commented on src/store/actions.ts
> +  return { ...userData, enumScope: Scope[userData.scope] };
Maybe we call this scopeAccess or something, I don’t like calling it enum since that would be like saying “varScope” you know…

2022-11-24 16:19 UTC, kitajchuk commented on src/api/types.ts
> +  enumScope: Scope;
For the store just maybe have a unique user interface since we only have the JWT data there anyway.

2022-11-24 16:37 UTC, kitajchuk commented on src/store/actions.ts
> +  const userData = parseJwt(token);
As I was mentioning above you would change the user type in the store as described and use it here as well as the type passed to the Promise generic

2022-11-24 16:43 UTC, kitajchuk commented on src/api/types.ts
> +  enumScope: Scope;
To me it also looks like you need to add all this user login properties to the cypress fixture for it as well please.

2022-11-25 08:25 UTC, EgleHelms commented on src/containers/internal/navi/index.tsx
> +                  <option>currentServiceProvider.name</option>
yeah, that was not smart. hmm, then I guess I need another condition here, to map the values when it is only the currentServiceProvider is available e.g. for SP and account users, they wont see other ones.

2022-11-25 10:53 UTC, EgleHelms commented on src/store/actions.ts
> +import { Scope } from "./types";
hmm, here I separated them because using it like this: scopeAccess: Scope[userData.scope] is not allowed if it is used as a type, since then it does not pick up the value, just type. Do you know a better way to do this?

2022-11-25 10:59 UTC, EgleHelms commented on src/components/scoped-access.tsx
> +
Ahm, it was not about showing some message, but more like if you pass a noAccessRender component, it can render something else for different scopes. 
E.g. usage I was thinking this for was - when clicking on "Accounts" in the Nav admin  and SP scope user will see Accounts list, but I would render "edit page" the account scope user for the account he is part of. And then if there is no noAccessRender component passed, then I would then just use null
Does it make sense?

2022-11-25 15:18 UTC, kitajchuk commented on src/components/scoped-access.tsx
> +
I think pieces of UI should be wrapped vs this approach if I’m understanding correctly. Just wrap the edit button with the scoped access.

2022-11-25 15:21 UTC, kitajchuk commented on src/store/actions.ts
> +import { Scope } from "./types";
Ha ya that makes sense. I always forget that with enums. My preference for specifying type imports is probably annoying for this reason 🙃

2022-11-25 16:33 UTC, EgleHelms commented on src/api/types.ts
> +  enumScope: Scope;
if I update the cypress fixture, I cannot resolve the typing of UserLogin in the test/index.tsx I am not sure why. because that is an extension of User interface. it has all the relevant fields still complains somehow.

2022-11-25 16:34 UTC, EgleHelms commented
> Some changes. For the tests to work you will have to mock the user scope and login since that’s not the default. You can see the test utils here: https://github.com/jambonz/jambonz-webapp/blob/main/src/test/index.tsx. This may be a bit more challenging since we don’t currently do a login example in any of our component tests.
> 
> We don’t currently have any flows for this. To test scopes we’d need to be able to mock the store more flexibly for our tests.
> 
> You notice currently we allow passing auth context props but we use the store provider verbatim. We’d need to use the store context similar to how we do with auth in the test provider and support passing store props as well. May be more trouble than it’s worth for this PR but you could take a shot st it if you want. I would separate them out as authProps and storeProps on the test provider. If you do you may have to update other tests to pass props the new way.

I was trying to resolve this but wasn't able to wrap my head around how to pass the values correctly. I will try again Monday. Feel free to push into this branch anything you want to help move this forward. Thanks.

2022-11-28 09:47 UTC, EgleHelms commented on src/test/index.tsx
> +    <StateContext.Provider value={storeProps}>
@kitajchuk I try to pass the store here, and it should be part of the "...restProps" but they don't travel into the Wrapper of the test. I don't understand why.

2022-11-28 14:54 UTC, kitajchuk commented on src/test/index.tsx
> +    <StateContext.Provider value={storeProps}>
This isn’t really how I was imagining this implementation here. It can be much simpler (we don’t have to replicate the useReducer stuff—that’s overkill. And the userJWT should not be here. You would set your user in the tests. Here we just want to “mock” it in so we can pass ad-hoc props to set global state and test components. I also wouldn’t merge auth props and store props like this because it is messy. I was thinking separating them on the props type as authProps and storeProps and spreading them separately on each context. Maybe just revert this commit and I can branch off this and show you what I was thinking 🤔

2022-11-28 15:03 UTC, EgleHelms commented on src/test/index.tsx
> +    <StateContext.Provider value={storeProps}>
@kitajchuk reverted.

2022-11-29 14:33 UTC, EgleHelms commented
@kitajchuk @davehorton  can this be merged with your changes added?

2022-11-29 15:14 UTC, kitajchuk approved these changes

2022-11-29 15:15 UTC, kitajchuk commented
> > @kitajchuk @davehorton can this be merged with your changes added?
> 
> What changes were those? I dont think I have any changes on the main branch of this repo

I believe yes since you merged my PR into this branch 👍

2022-11-29 15:19 UTC, merged