Optional account call limits
jambonz/jambonz-webapp pull request #162
Opened 2022-12-06 15:04 UTC by EgleHelms

Optional env is: VITE_APP_ENABLE_ACCOUNT_LIMITS_ALL

Enables new choosing units and getting accordingly the new fields:
![image](https://user-images.githubusercontent.com/63853378/205947159-02c843e1-c8e1-4ada-a689-2b98909d7a78.png)

![image](https://user-images.githubusercontent.com/63853378/206221718-dbf86af6-9aef-4a2f-a664-e1c6d5de015c.png)

2022-12-07 13:02 UTC, davehorton commented
When "sessions" are selected from the dropdown, are you going to change the labels e.g. to then read "Max Sessions" instead of "Max minutes"?

2022-12-07 13:57 UTC, EgleHelms commented
I will check once more to make sure it is correct.

2022-12-07 14:46 UTC, EgleHelms commented
You are right, changing it back is not working, need to resolve the state.

2022-12-07 15:34 UTC, davehorton approved these changes

2022-12-07 15:35 UTC, davehorton commented
@kitajchuk if you have time please weigh in here, but we need this merged to progress so if you don't have time I will be merging today

2022-12-07 15:36 UTC, EgleHelms commented
@davehorton fixed the typo, should be good now. I think this still needs a functional test. I keep getting unauthorized when I test with the main branch, not sure why.

2022-12-08 16:04 UTC, kitajchuk requested changes
Some changes I'd like to see here 👍

2022-12-08 16:04 UTC, kitajchuk commented on src/components/forms/local-limits.tsx
> +          <React.Fragment key={category}>
Okay, so looking at this locally this is no good—this is a ton of copy pasted code. We always want to refactor in order to keep things DRY and not just dupe like code around. Here's my suggestion based on what is different and what is the same between the two.

Assign `filteredLimits` to a var conditionally based on the env and use that for the map: 

```tsx
const filteredLimits = import.meta.env.VITE_APP_ENABLE_ACCOUNT_LIMITS_ALL
    ? LIMITS.filter((limit) =>
        unit === "sessions"
          ? !limit.category.includes("minutes")
          : limit.category.includes("minutes")
      )
    : LIMITS.filter(
        (limit) =>
          !limit.category.includes("license") &&
          !limit.category.includes("minutes")
      );
```

Return a single render tree and just wrap the selector in an env condition and use `filteredLimits` for the map:

```tsx
return (
    <>
      {import.meta.env.VITE_APP_ENABLE_ACCOUNT_LIMITS_ALL && (
        <>
          <label htmlFor="units">Units</label>
          <Selector
            id="units"
            name="units"
            value={unit}
            options={LIMIT_UNITS}
            onChange={(e) => setUnit(e.target.value)}
          />
        </>
      )}
      {filteredLimits.map(({ category, label }) => {
        return (
          <React.Fragment key={category}>
            <label htmlFor={category}>{label}</label>
            <input
              ref={(el: HTMLInputElement) => {
                if (inputRef && inputRef.current) {
                  inputRef.current[category] = el;
                }
              }}
              id={category}
              type="number"
              name={category}
              placeholder="Enter quantity (0=unlimited)"
              min="0"
              value={updateLimitValue(category)}
              onChange={(e) => {
                const limit = localLimits.find((l) => l.category === category);
                const value = e.target.value ? Number(e.target.value) : "";

                if (limit) {
                  setLocalLimits(
                    localLimits.map((l) =>
                      l.category === category ? { ...l, quantity: value } : l
                    )
                  );
                } else {
                  setLocalLimits([
                    ...localLimits,
                    { category, quantity: value },
                  ]);
                }
              }}
            />
          </React.Fragment>
        );
      })}
    </>
  );
```

2022-12-08 17:12 UTC, EgleHelms commented
> Some changes I'd like to see here +1

applied the changes.

2022-12-09 12:46 UTC, davehorton approved these changes

2022-12-09 15:57 UTC, kitajchuk approved these changes

2022-12-10 14:23 UTC, davehorton commented
@EgleHelms @kitajchuk I have merged the jambonz-api-server branch to main so in your further testing pls test against the main branch of jambonz-api-server

2022-12-10 14:24 UTC, davehorton commented
@EgleHelms @kitajchuk it looks like review comments have been addressed?  Is this branch ready to merge?

2022-12-10 16:24 UTC, kitajchuk commented
> @EgleHelms @kitajchuk it looks like review comments have been addressed? Is this branch ready to merge?

Yes smash the button 👍

2022-12-10 17:00 UTC, merged