Combine account user lists for carriers and speech
jambonz/jambonz-webapp pull request #186
Opened 2023-01-25 08:46 UTC by EgleHelms

This PR combines Carriers and Speech credential lists for account user and disables Filtering according to the account
Account user views for these lists:

![image](https://user-images.githubusercontent.com/63853378/214517739-7aee90d1-0e0c-4173-b029-de0240922b7d.png)

![image](https://user-images.githubusercontent.com/63853378/214517899-6e962620-22c1-4374-afee-5beb56655465.png)

API server small change to have Speech /SP call act the same way as Carriers: https://github.com/jambonz/jambonz-api-server/pull/98  This way the implementation is the same.

2023-01-26 14:18 UTC, davehorton commented
This is not quite working properly.  It does work properly for carriers, but not for speech.  Here are steps to illustrate:

- as admin user, create an account level user 
- as admin user, add a speech credential at the SP level (in my case, google)
- log out and back in as account user
- create a speech credential (in my case, Azure) and save it
- you are returned to the speech credential list screen with only google showing.  

Note: the Azure credential was in fact added.  If I try to add it again I get a duplicate

2023-01-26 14:25 UTC, davehorton requested changes
speech credentials added by account user disappear

2023-01-26 14:49 UTC, davehorton commented
Actually, the problem that I had above was related to not running the latest jambonz-api-server.  However, it points up a backwards compatibility issue -- account level credentials added prior to someone upgrading this version will disappear.

2023-01-26 14:54 UTC, EgleHelms commented
@davehorton  pointed out a backward compatibility issue this will create. We need to rethink the solution on the webapp and api-server.

2023-01-30 15:36 UTC, davehorton approved these changes

2023-01-30 15:36 UTC, merged