feat: add app_json to application
jambonz/jambonz-webapp pull request #188
Opened 2023-01-28 11:46 UTC by xquanluu

2023-01-28 15:23 UTC, davehorton requested changes

2023-01-28 15:23 UTC, davehorton commented on src/containers/internal/views/applications/form.tsx
> +      required: callHookRequired,
Actually, I think call_hook is still required, even if you put in app_json. The reason is that without this, we won't have a base URL to use to resolve relative URLs in action hooks.  Say for example your app_json has a `gather` which has an `actionHook` property of "/transcript".  Without the base URL from the call hook we would not be able to invoke the webhook in the gather

2023-01-28 15:23 UTC, davehorton commented on src/containers/internal/views/applications/form.tsx
> +        <fieldset>
I'd like a few changes to the UI.  Here is what this looks like now:
![image](https://user-images.githubusercontent.com/1884973/215274496-b7aaa37b-10ba-45f0-aeed-49641114467b.png)

Please make these changes:
1. Move it to the bottom of the form under the speech credentials
2. Have it hidden by a checkbox labeled "Override webhook for initial application".  This would be like how we do outbound authentication in the Carrier panel for instance:

![image](https://user-images.githubusercontent.com/1884973/215274671-da795c94-8feb-48cb-b0e5-f8cd6547511e.png)

![image](https://user-images.githubusercontent.com/1884973/215274679-9be3fee9-199f-4956-b7e1-425a9bf92d2c.png)

3. Make the input a multi-line edit control showing 4 lines.
4. Finally, add an env variable that if set hides this entire feature.  By default it will be available but someone deploying their own system could turn if off globally if they so desired

2023-01-28 15:29 UTC, davehorton commented
I've opened issue #189 please tag that in future commits on this branch

2023-01-28 23:48 UTC, xquanluu commented on src/containers/internal/views/applications/form.tsx
> +      required: callHookRequired,
fixed

2023-01-29 01:54 UTC, davehorton commented
Not quite working yet.  If I create a new application, click the checkbox and add app json and save, it is saved to the database.  However, if I then click on the application to edit it, the checkbox is unchecked so the app json -- which does exist -- is hidden.

Also, the entry field is still an input but I would like it to be a multi-line input

2023-01-29 13:17 UTC, davehorton requested changes

2023-01-29 13:17 UTC, davehorton commented on src/containers/internal/views/applications/form.tsx
>                <input
This is still an input.  Is it not possible to use a textarea here?

2023-01-31 21:03 UTC, davehorton commented
@kitajchuk not sure if you have time to take a quick look, but I want to use a textarea in a Checkzone, below is what it looks like if I simply swap the textarea in for the input, would you have any suggestions on improving the UI?

![image](https://user-images.githubusercontent.com/1884973/215882594-05ca6d6a-7efe-4a20-83e3-9c4419c1ef85.png)

2023-02-09 21:37 UTC, davehorton approved these changes

2023-02-13 14:04 UTC, davehorton requested changes
Currently, if there is an error we get an error message but the input text is removed entirely so we can't easily edit it so as to fix it.  It would be better if when the PUT fails because of an invalid app_json entry that we leave that entry in place so it can be studied and fixed with the help of the error message.

2023-02-15 15:34 UTC, davehorton approved these changes

2023-02-15 15:35 UTC, davehorton approved these changes

2023-02-15 15:35 UTC, merged