feat: nvidia tts/stt speech
jambonz/jambonz-webapp pull request #201
Opened 2023-02-10 07:46 UTC by xquanluu

2023-02-10 19:36 UTC, davehorton requested changes
Don't we need a list of languages and voices for Nvidia so we can populate the speech dropdowns in the Application form

2023-02-10 19:36 UTC, davehorton commented on src/vendor/types.ts
> +  | "NVIDIA";
Can you change this to "Nvidia", and while you are at it change "deepgram" to "Deepgram" for consistency

2023-02-12 06:45 UTC, xquanluu commented on src/vendor/types.ts
> +  | "NVIDIA";
Fixed All review comments

2023-02-12 18:51 UTC, davehorton requested changes

2023-02-12 18:51 UTC, davehorton commented on src/vendor/index.tsx
> +  {
The list of vendors is now getting quite long, so whenever we display it in a dropdown please display it in alphabetic order.  This would be on both the speech credentials screen as well as the application screen.

2023-02-13 13:37 UTC, davehorton approved these changes

2023-02-13 13:37 UTC, merged