feat: forgot password
jambonz/jambonz-webapp pull request #218
Opened 2023-03-24 05:12 UTC by xquanluu

2023-03-30 21:43 UTC, xquanluu commented
Hi @davehorton  could you please also review this PR?

2023-03-30 21:48 UTC, davehorton requested changes
We need this feature to be optional -- only shown the user if an env var is configured, because they may not have implemented the mail API interface.

2023-03-30 23:51 UTC, davehorton submitted a review, later dismissed

2023-05-11 01:32 UTC, davehorton approved these changes

2023-05-11 01:32 UTC, merged