upgrade wavesuffer to 7.3.4
jambonz/jambonz-webapp pull request #329
Opened 2023-10-12 05:38 UTC by xquanluu

2023-10-16 09:10 UTC, xquanluu commented
<img width="1339" alt="Screenshot 2023-10-12 at 12 41 14" src="https://github.com/jambonz/jambonz-webapp/assets/110280845/4fdc3e7d-6ed8-4d8c-a235-cbe80fe4bc86">

2023-10-16 09:12 UTC, davehorton requested changes

2023-10-16 09:12 UTC, davehorton commented on src/containers/internal/views/recent-calls/player.tsx
> +  const waveSuferRef = useRef<WaveSurfer | null>(null);
can you fix the typos?  "waveSufer" should be "waveSurfer"

2023-10-16 09:17 UTC, davehorton commented
There is no change in functionality here, is that right?  Just upgrading to the most recent version of wavesurfer?

2023-10-16 10:07 UTC, xquanluu commented
yes it's correct

The timeline ruler is more detail in 0.2 second

2023-10-16 10:29 UTC, davehorton commented
ok great.  After fixing the comment above can you deploy to jambonz.me for testing?

2023-10-16 23:41 UTC, xquanluu commented
fixed typo issue

2023-10-18 17:54 UTC, davehorton approved these changes

2023-10-18 17:55 UTC, merged