add elevenlabs
jambonz/jambonz-webapp pull request #330
Opened 2023-10-12 08:29 UTC by xquanluu

https://github.com/jambonz/jambonz-webapp/issues/328

2023-10-12 11:59 UTC, davehorton commented
Change Model Id to just Model, and show the other two models as well
![image](https://github.com/jambonz/jambonz-webapp/assets/1884973/c435b35e-a6e4-468b-90d6-46a93a357493)

2023-10-12 12:00 UTC, davehorton commented
The names should just be "multilingual v2", "multilingual v1", and "monolingual v1"

2023-10-12 12:29 UTC, xquanluu commented
fixed

2023-10-12 13:00 UTC, davehorton commented
In the dropdown list of voices in the Application view when you select ElevenLabs you currently get a list of voice names, ordered as they are returned from ElevenLabs in the GET /voices.  Instead, please show them in alphabetic order.  Also, instead of 
```
Rachel
```
show it as
```
Rachel - american, calm, young, female, narration
```
where those values after the dash are the values in the `labels` property of the voice object that is returned, e.g.
![image](https://github.com/jambonz/jambonz-webapp/assets/1884973/6b336e43-f954-411f-a07f-425f2c8ee226)

2023-10-12 13:14 UTC, davehorton commented
If the user chooses "monolingual v1" as the model, only the English language should be offered

2023-10-12 13:36 UTC, davehorton requested changes

2023-10-12 13:36 UTC, davehorton commented on src/vendor/speech-synthesis/elevellabs-speech-synthesis-lang.ts
> +export const languages: VoiceLanguage[] = [
Since ElevenLabs has a public api to get voices, instead of hardcoding this list, can we retrieve it dynamically when the Application view comes up - or probably better yet when the speech synthesis dropdown on the Applications panel is selected to be Eleven Labs?

The GET /Voices api can be done with no authentication - in which you get back the standard list of voices -- or it can be done with the api-key of the user, in which case you get back the standard voices plus any cloned voices that the user has added.  So we want to use the authenticated version, grabbing the api key that the user has entered (this presumes that if they select ElevenLabs on the Application view they have previously entered a speech credential for Eleven Labs -- if this is not the case, then just use the unauthenticated version of the API and go with that.

So the api call (in curl) will look like this
```
curl -X 'GET' \
  'https://api.elevenlabs.io/v1/voices' \
  -H 'accept: application/json' \
  -H 'xi-api-key: <api-key>'
```

I will give you my api key separately to use for testing, as I have cloned my own voice and added it to my account

2023-10-13 12:11 UTC, davehorton commented
Also, one further request.  In the Voices payload response there is a property called "category".  When creating the display name in the dropdown, if the category value is anything other than "premade", please put it next to the name in parentheses.

For instance, Rachel is a premade name so it would look like as I suggested above:
```
Rachel - american, calm, young, female, narration
```
However, DaveH is a cloned voice:
```
        {
            "voice_id": "TwVPyTHwMlVlXTKVW83m",
            "name": "DaveH",
            "samples": [
                {
                    "sample_id": "klBmsEttYjvdik5UYK9C",
                    "file_name": "dave-3mins.mp3",
                    "mime_type": "audio/mpeg",
                    "size_bytes": 646848,
                    "hash": "a50c833c62f988b25b28f42ce4bad0a2"
                }
            ],
            "category": "cloned",
            "fine_tuning": {
                "language": null,
                "is_allowed_to_fine_tune": false,
                "fine_tuning_requested": false,
                "finetuning_state": "not_started",
                "verification_attempts": null,
                "verification_failures": [],
                "verification_attempts_count": 0,
                "slice_ids": null,
                "manual_verification": null,
                "manual_verification_requested": false
            },
            "labels": {
                "accent": "American",
                "sex": "male",
                "type": "slightly raspy",
                "age": "50+"
            },
```
So it should appear as:
```
DaveH (cloned) - American, male, slightly raspy, 50+
```

2023-10-14 11:10 UTC, davehorton submitted a review, later dismissed

2023-10-15 11:07 UTC, davehorton commented
@xquanluu there is a bug when setting a voice in the Application view.  When I save it, it does use that name but when I come back in again to the Application page it shows the voice as the first one in the list (Adam) not the one I selected

https://www.loom.com/share/864a6003e49b4e3cb36dabf6287880f3?sid=3a6d9145-285a-42da-979f-565294bd3707

2023-10-16 07:41 UTC, xquanluu commented
Fixed

2023-10-16 08:21 UTC, davehorton approved these changes

2023-10-16 08:21 UTC, merged