Send options ping sip gateway
jambonz/jambonz-webapp pull request #363
Opened 2023-12-12 07:11 UTC by xquanluu

https://github.com/jambonz/jambonz-webapp/issues/362

<img width="1400" alt="Screenshot 2023-12-12 at 14 02 48" src="https://github.com/jambonz/jambonz-webapp/assets/110280845/045e9435-114a-4b8b-8a20-7c59078a1f3d">

2024-03-30 13:16 UTC, davehorton requested changes

2024-03-30 13:16 UTC, davehorton commented on src/containers/internal/views/carriers/form.tsx
> +                          <label
I dont know where the label text is kept but I would like it to be "send OPTIONS ping"

2024-04-15 09:58 UTC, xquanluu commented on src/containers/internal/views/carriers/form.tsx
> +                          <label
the label text is here: https://github.com/jambonz/jambonz-webapp/pull/363/files#diff-512d63808fe31447ace3dfaffff744446e16489c2f767085211a9d70d2f300deR1141

And Yes this just apply to outbound gateway only

2024-04-15 11:19 UTC, davehorton approved these changes

2024-04-15 11:19 UTC, merged