moved building to Dockefile instead of entrypoint
jambonz/jambonz-webapp pull request #39
Opened 2022-02-09 14:37 UTC by radicaldrew

running jambonz on a minimal Kubernetes cluster with 2 GB memory per node.  the webapp did ran out of resources building on initialisation of the container.

2022-02-10 16:33 UTC, kitajchuk requested changes
I've made some notes on changes I would like to see in order to make this a robust solution for the jambonz webapp, both for production and local development environments 👍

2022-02-10 16:33 UTC, kitajchuk commented on public/index.html
> +    <script>var APP_API_BASE_URL = 'app_url';</script>
I would prefer an explicit `window.APP_API_BASE_URL = "APP_URL"` here. Better yet, we could make this possibly more robust in case any more `env` vars need to be added in the future. Something like:

```js
window.JAMBONZ = {
  APP_API_BASE_URL: "APP_URL"
};
```

2022-02-10 16:39 UTC, radicaldrew commented on src/components/blocks/Nav.js
> +        baseURL: APP_API_BASE_URL,
Will this allow the webapp to work properly in EC2 enviroment as well as the Docker Image?

2022-02-10 16:42 UTC, radicaldrew commented on entrypoint.sh
> +app_url="${REACT_APP_API_BASE_URL:-http://$PUBLIC_IPV4:$API_PORT/$API_VERSION}"
You are correct with proper naming, the reason for the lowercase was the entrypoint.sh changes
with sed.   I had an issue with sed not rewriting with uppercase.  This might need to be changed.

2022-02-10 16:45 UTC, davehorton commented on src/components/blocks/Nav.js
> +        baseURL: APP_API_BASE_URL,
agree, and just for clarity, what I currently have to do when deploying on EC2 via a cloudformation script is to have a userdata script that runs the build.  This takes quite a long time, and so the user experience is poor, in that after running the CF script you assume the portal will be available shortly but it can take 5-10 mins.

This is the part of the userdata script I am referring to:
```bash
echo "REACT_APP_API_BASE_URL=http://${PUBLIC_IPV4}/api/v1" > /home/admin/apps/jambonz-webapp/.env 
echo "REACT_APP_MOBILE_BREAKPOINT=767px" >> /home/admin/apps/jambonz-webapp/.env 
echo "REACT_APP_ENABLE_SUBSPACE=1" >> /home/admin/apps/jambonz-webapp/.env 
cd /home/admin/apps/jambonz-webapp && npm run build 
```
Whatever solution we come up with, I want to eliminate that `npm run build` and instead do that in my packer script which creates the AMI image

2022-02-10 16:46 UTC, kitajchuk commented on src/components/blocks/Nav.js
> +        baseURL: APP_API_BASE_URL,
This would work for the docker because the build is produced in the image via the Dockerfile now in this PR and the entrypoint script will do the sed replace on the index file. So restart cycles should work with these changes for docker containers.

For an EC2 instance you will need to create the build and utilize the entrypoint script to run the application. These changes will work for any environment so long as you use the entrypoint script to serve the app.

2022-02-10 17:16 UTC, radicaldrew commented on src/components/blocks/Nav.js
> +        baseURL: APP_API_BASE_URL,
Then the entry point  should add the entire script tag and not just do a replace.
This way you can have it optional in case your not using that  APP_API_BASE_URL

2022-02-10 17:22 UTC, davehorton commented on src/components/blocks/Nav.js
> +        baseURL: APP_API_BASE_URL,
I don't want to use the entrypoint script necessarily on EC2.  I'd be happy to build a machine image (via packer) that did the `npm build` as part of the machine image, and then doing the `sed` command in my userdata script.  Can I do it that way?

Will it still work for local dev?  What about someone running on their own server?  Can they still do a simple `npm build` and then be able to run?

I'm not quite clear on how the various scenarios will be handled:
- local dev
- docker (kubernetes)
- EC2 AMI deployed via CF
- random cloud instance where someone manually does a git pull from the jambonz-webapp repo and needs to start it up

2022-02-10 17:29 UTC, radicaldrew commented on src/components/blocks/Nav.js
> +        baseURL: APP_API_BASE_URL,
The pull request as of right now only supports that variable APP_API_BASE_URL. This way would not work for the other scenarios.  Brandon's way of using both variables depending on environment variables would work because the build would use either or.

2022-02-10 21:10 UTC, davehorton commented on src/components/blocks/Nav.js
> +        baseURL: APP_API_BASE_URL,
for the EC2 AMI deployed via CF I am already doing some other similar adjustment of config files via a userdata script, including "sed" operations, so I am happy to put it there.

So the only outstanding scenario is someone doing a random manual build.  We are basically already telling that person about how to set up the .env file currently, do we have a fairly straightforward option like that?

2022-02-10 21:41 UTC, radicaldrew commented on src/components/blocks/Nav.js
> +        baseURL: APP_API_BASE_URL,
what about a script that does that can be called from npm scripts so can be add to npm run start before react-scripts start?

2022-02-11 05:15 UTC, kitajchuk commented on src/components/blocks/Nav.js
> +        baseURL: APP_API_BASE_URL,
We could create a script that would just include a portion of `entrypoint.sh` like for an ad-hock VM build like on an EC2 instance or what have you. Say we put this in a `bootsrap.sh` file:

```shell
#!/bin/sh
PUBLIC_IPV4="$(curl --fail -qs whatismyip.akamai.com)"
API_PORT="${API_PORT:-3000}"
API_VERSION="${API_VERSION:-v1}"
echo "REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL:-http://$PUBLIC_IPV4:$API_PORT/$API_VERSION}" > .env
```

Then you would just `npm run build` and `npm run serve` as needed. Presumably this would work on any host environment assuming the repo was cloned and they go to town. I don't really know how much we need a single command to accommodate this scenario so much as good documentation in the readme. Assuming the ad-hock/random manual build on, say, an EC2 instance the steps are basically:

```shell
# clone repo
git clone git@github.com:jambonz/jambonz-webapp.git
cd jambonz-webapp

# install node_modules
npm install

# bootstrap env for dynamic api url
./bootstrap.sh

# build static production bundle
npm run build

# serve static site
npm run serve
```

Thoughts?

2022-02-11 12:46 UTC, davehorton commented on src/components/blocks/Nav.js
> +        baseURL: APP_API_BASE_URL,
I agree that as long as we have a decent readme we dont necessarily need one script to do it all.  The above looks good to me, but would't `bootstrap.sh` need to export those variables?

2022-02-11 16:50 UTC, kitajchuk commented on src/components/blocks/Nav.js
> +        baseURL: APP_API_BASE_URL,
I don't think so since it writes the `REACT_APP_API_BASE_URL` to `.env`. Then the CRA scripts will use that during the build with a `NODE_ENV` of `production`.

2022-02-11 17:17 UTC, davehorton commented on src/components/blocks/Nav.js
> +        baseURL: APP_API_BASE_URL,
oh sorry I did not see the end of that line where it redirected the output. Doh!

2022-02-11 21:12 UTC, davehorton commented
@radicaldrew at this point are you comfortable with making the changes requested?

2022-02-13 15:30 UTC, radicaldrew commented
> @radicaldrew at this point are you comfortable with making the changes requested?

Yes I will make these changes and test.

2022-02-15 16:12 UTC, davehorton commented
anything new on this @radicaldrew ?

2022-02-16 16:30 UTC, radicaldrew commented
> Contributor

I will be committing the latest changes today or tomorrow.

2022-02-17 11:45 UTC, radicaldrew commented
I made a new commit for this based on all suggestions.
please review.     NODE_ENV should be set during build. so development should use the enviroment variable
and production uses the window.JAMBONZ.APP_API_BASE_URL.         
I also updated the deployment to add script tag to index.html with the correct api url

2022-02-17 13:05 UTC, davehorton commented
I tested running a local dev environment, and that works:
```
npm install
npm start
```
Next, I tested doing a local build and trying to run the build, and that did not work -- I got a blank screen:
```
npm install
npm run build
npm run serve
```
I havent yet tested docker, but the above should work, shouldn't it?

2022-02-17 13:09 UTC, radicaldrew commented
> I tested running a local dev environment, and that works:
> 
> ```
> npm install
> npm start
> ```
> 
> Next, I tested doing a local build and trying to run the build, and that did not work -- I got a blank screen:
> 
> ```
> npm install
> npm run build
> npm run serve
> ```
> 
> I havent yet tested docker, but the above should work, shouldn't it?

Those two scenarios should work, let me check out my repo and test again
also build and test new docker image.

2022-02-17 13:19 UTC, radicaldrew commented
@davehorton  No does not work correctly in that scenario. I am fixing.
I only added the window.JAMBONZ.APP_API_BASE_URL in deployment
so when I do npm run build & npm run serve I get error window.JAMBONZ is undefined.
I am fixing.

2022-02-17 13:37 UTC, radicaldrew commented
Do you think we should change this to just (window.JAMBONZ) and not with NODE_ENV
so to change the base url just add it to the index.html?

2022-02-17 13:56 UTC, davehorton commented
yes - I think if window.JAMBONZ is not undefined, it means that we deliberately inserted the URL into index.html.  In that case, I can think of no scenarios where we would not want to use that as the api url

2022-02-17 14:10 UTC, davehorton commented
I can confirm the local build and test scenario works for me now.

2022-02-17 14:12 UTC, radicaldrew commented
> I can confirm the local build and test scenario works for me now.

I removed the NODE_ENV in the latest commit. so in order to use the new baseurl all we need to do is add it to the
index.html in the deployment. tested both scenarios

2022-02-17 14:53 UTC, davehorton commented
could you rebase to the latest main?

2022-02-17 14:55 UTC, radicaldrew commented
> could you rebase to the latest main?

done

2022-02-17 14:57 UTC, davehorton commented
@kitajchuk could you review the latest changes when you have a chance?  I will meanwhile test on a native EC2 VM deployment as well as kubernetes.

2022-02-23 03:54 UTC, kitajchuk approved these changes

2022-02-23 04:00 UTC, kitajchuk requested changes
I have made a couple notes on simple things I'd like to see to wrap this up. I tested local dev server and local build+serve and both work. I'm assuming the docker builds work as well as I saw both @radicaldrew and @davehorton had some back and forth there with the end result being: it works—yay!

The final thing I would like to see is either squash the commits on this PR or please make sure to use the squash+merge strat when smashing the button once these couple changes are completed here soon 👍

2022-02-23 10:04 UTC, radicaldrew commented on src/components/blocks/Sbcs.js
> +/* eslint-disable no-undef */
this was resolved

2022-02-23 10:04 UTC, radicaldrew commented on src/constants.js
> +let { REACT_APP_API_BASE_URL } = process.env;
this was resolved

2022-02-23 10:04 UTC, radicaldrew commented on src/contexts/ShowMsTeamsContext.js
> +/* eslint-disable no-undef */
removed

2022-02-23 12:40 UTC, merged